project_id = "ffqcwcbrfzvytsokkrln"

[functions.import-lead-from-sheets]
verify_jwt = false

[functions.facebook-leads-webhook]
verify_jwt = false

[functions.send-task-telegram-reminder]
verify_jwt = false
